---
apiVersion: v1
kind: Service
metadata:

  name: quorum-node1
  namespace: quorum
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node1
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node1-deployment
  # NodePort | ClusterIP | LoadBalancer
  type: LoadBalancer
  ports:
    - name: tm-manager
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: rpc-listener
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: wsport
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 30303
      targetPort: 30303

---
apiVersion: v1
kind: Service
metadata:

  name: quorum-node2
  namespace: quorum
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node2
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node2-deployment
  # NodePort | ClusterIP | LoadBalancer
  type: LoadBalancer
  ports:
    - name: tm-manager
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: rpc-listener
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: wsport
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 30303
      targetPort: 30303

---
apiVersion: v1
kind: Service
metadata:

  name: quorum-node3
  namespace: quorum
  labels:
    app: qubernetes
    tier: backend
    name: quorum-node3
spec:
  selector:
    app: qubernetes
    tier: backend
    name: quorum-node3-deployment
  # NodePort | ClusterIP | LoadBalancer
  type: LoadBalancer
  ports:
    - name: tm-manager
      protocol: TCP
      port: 9001
      targetPort: 9001
    # default 8545
    - name: tm-tessera-third-part
      protocol: TCP
      port: 9080
      targetPort: 9080
    # default 8545
    - name: rpc-listener
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: wsport
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: quorum-listener
      protocol: TCP
      port: 30303
      targetPort: 30303
